apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yaml convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file compose.yaml convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mastodon-net: "true"
        io.kompose.service: app
    spec:
      containers:
        - image: santisbon/mastodon-bot
          name: bot-app
          ports:
            - containerPort: 8008
          resources: {}
      hostname: bot-app
      restartPolicy: Always
status: {}
