version: "3.8"

services:
  app:
    image: santisbon/mastodon-bot
    ports:
      - "8008:8008"
    networks:
      - mastodon-net
    depends_on:
      - cache
    platform: linux/arm64
    container_name: bot-app
    hostname: bot-app
    build:
      context: .
      dockerfile: Dockerfile-app
  cache:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mastodon-net
    command: redis-server --save 60 1 --loglevel warning
    platform: linux/arm64
    container_name: bot-redis
    hostname: bot-redis
    volumes:
      - type: volume
        source: redis-data
        target: /data

volumes:
  redis-data:

networks:
  mastodon-net: