mastodon:
  base_url: https://some.mastodon.instance
  access_token: YOUR-BOT-API-ACCESS-TOKEN

rss:
  poll_seconds: 300
  subscriptions:
    - https://nitter.net/WSJ/rss
    - https://nitter.net/Reuters/rss

backend.redis:
    redis_args:
        host: bot-redis
