kind: PersistentVolume
apiVersion: v1
metadata:
  name: cache-pv
spec:
  storageClassName: localdisk-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/botcache
